# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Stand Alone Complex
tagline:             ''
description:         'Hello Stranger!'
url:                 http://youngoo.github.io/
baseurl:             http://youngoo.github.io/
paginate:            5

# About/contact
author:
  name:              Vim Tseng
  url:               https://twitter.com/youngoo
  email:             vim.tseng@gmail.com

# Custom vars
version:             1.0.0
